### ISSUE TITLE
Warnings when compiling "cli example.ino" and nothing is displayed on Serial monitor.

### ISSUE THREAD

**Issue by meltdown03** [trevor-makes/core#1]
``` c++
src/demo1.cpp: In function 'void loop()':
src/demo1.cpp:27:3: warning: invalid conversion from 'void (*)(core::cli::Tokens)' to 'core::cli::CommandFn {aka void (*)(core::cli::Args)}' [-fpermissive]
   };
   ^
src/demo1.cpp:27:3: warning: invalid conversion from 'void (*)(core::cli::Tokens)' to 'core::cli::CommandFn {aka void (*)(core::cli::Args)}' [-fpermissive]
src/demo1.cpp:28:29: warning: invalid conversion from 'const core::cli::Command*' to 'char' [-fpermissive]
   serial_cli.prompt(commands);
                             ^
In file included from src/demo1.cpp:3:0:
.pio/libdeps/megaatmega2560/core/include/core/cli.hpp:171:8: note:   initializing argument 1 of 'void core::cli::CLI<BUF_SIZE, HIST_SIZE, PRM_SIZE>::prompt(char) [with unsigned char BUF_SIZE = 80; unsigned char HIST_SIZE = 80; unsigned char PRM_SIZE = 20]'
   void prompt(char c) { prompt_.try_insert(c); }
        ^~~~~~
```

Those are the warnings when I try the `cli example.ino` example on my Mega2560. The IO example works fine though. I also don't get anything on the serial monitor. Unless it's not supposed to really do anything?

**Comment by trevor-makes** [comment]
Oof, the example was out of date. Needed `Tokens` -> `Args` and `prompt` -> `run_once`. I fixed it in [this commit](https://github.com/trevor-makes/core/commit/2db054f0853b16ca2c2893b44f2fed48526a391e), and added environment settings to allow building the examples from the core project itself.

The CLI example should give you a `>`prompt
- entering `add 1 2` should print `1 + 2 = 3`
- entering `echo "Hello World!"` should print `Hello World!`.

Thanks for checking out my library! I need to update some things for the Uno R4, so I'll take this opportunity to fix the missing documentation and see if anything else is broken.

**Comment by meltdown03** [comment]
Thank you, that got rid of the warnings and made it work.
